In [ ]:
! pip install nltk

## Import the data 

Link to data - https://www.kaggle.com/datasets/mdismielhossenabir/sentiment-analysis/data

In [2]:
import pandas as pd 
import numpy as np

In [12]:
df = pd.read_csv('sentiment_analysis.csv')

In [13]:
df

,Year,Month,Day,Time of Tweet,text,sentiment,Platform
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,2017,8,18,night,Don't angry me,negative,Facebook
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram
...,...,...,...,...,...,...,...
494,2015,10,18,night,"According to , a quarter of families under six...",negative,Twitter
495,2021,2,25,morning,the plan to not spend money is not going well,negative,Instagram
496,2022,5,30,noon,uploading all my bamboozle pictures of facebook,neutral,Facebook
497,2018,8,10,night,congratulations ! you guys finish a month ear...,positive,Twitter
498,2019,3,25,morning,"actually, I wish I was back in Tahoe. I miss...",negative,Instagram

In [4]:
df['sentiment'].unique()

array(['positive', 'negative', 'neutral'], dtype=object)

In [46]:
df['sentiment'].value_counts()

sentiment
neutral     199
positive    166
negative    134
Name: count, dtype: int64

In [10]:
df = df[['text','sentiment']]

In [7]:
df

                                                  text sentiment
0                What a great day!!! Looks like dream.  positive
1       I feel sorry, I miss you here in the sea beach  positive
2                                       Don't angry me  negative
3    We attend in the class just for listening teac...  negative
4                    Those who want to go, let them go  negative
..                                                 ...       ...
494  According to , a quarter of families under six...  negative
495      the plan to not spend money is not going well  negative
496    uploading all my bamboozle pictures of facebook   neutral
497   congratulations ! you guys finish a month ear...  positive
498   actually, I wish I was back in Tahoe.  I miss...  negative

[499 rows x 2 columns]

## using Vader and SIA

In [17]:
import nltk
from datasets import load_dataset
from nltk.sentiment import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
sia = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\vvenk\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [14]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\vvenk\AppData\Roaming\nltk_data...

True

### Understanding SIA

In [19]:
sentence = "This is a great tool for sentiment analysis!."
sentiment_scores = sia.polarity_scores(sentence)
print(sentiment_scores)

{'neg': 0.0, 'neu': 0.577, 'pos': 0.423, 'compound': 0.6588}

In [21]:
def analyze_sentiment_nltk(review):
    score = sia.polarity_scores(review)
    final_score = score['compound']
    if final_score > 0.4:
        return 'positive'
    elif final_score >= -0.3 and final_score <= 0.4:
        return 'neutral'
    else :
        return 'negative'

In [28]:
df['predicted_sentiment_nltk'] = df['text'].apply(analyze_sentiment_nltk)

In [29]:
df

,Year,Month,Day,Time of Tweet,text,sentiment,Platform,predicted_sentiment_nltk,prediction_correctness_nltk
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter,positive,1
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook,neutral,0
2,2017,8,18,night,Don't angry me,negative,Facebook,positive,0
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook,neutral,0
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram,neutral,0
...,...,...,...,...,...,...,...,...,...
494,2015,10,18,night,"According to , a quarter of families under six...",negative,Twitter,negative,1
495,2021,2,25,morning,the plan to not spend money is not going well,negative,Instagram,neutral,0
496,2022,5,30,noon,uploading all my bamboozle pictures of facebook,neutral,Facebook,negative,0
497,2018,8,10,night,congratulations ! you guys finish a month ear...,positive,Twitter,positive,1
498,2019,3,25,morning,"actually, I wish I was back in Tahoe. I miss...",negative,Instagram,neutral,0

In [30]:
df['prediction_correctness_nltk'] = np.where(df['sentiment']==df['predicted_sentiment_nltk'],1,0)

In [31]:
df

,Year,Month,Day,Time of Tweet,text,sentiment,Platform,predicted_sentiment_nltk,prediction_correctness_nltk
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter,positive,1
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook,neutral,0
2,2017,8,18,night,Don't angry me,negative,Facebook,positive,0
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook,neutral,0
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram,neutral,0
...,...,...,...,...,...,...,...,...,...
494,2015,10,18,night,"According to , a quarter of families under six...",negative,Twitter,negative,1
495,2021,2,25,morning,the plan to not spend money is not going well,negative,Instagram,neutral,0
496,2022,5,30,noon,uploading all my bamboozle pictures of facebook,neutral,Facebook,negative,0
497,2018,8,10,night,congratulations ! you guys finish a month ear...,positive,Twitter,positive,1
498,2019,3,25,morning,"actually, I wish I was back in Tahoe. I miss...",negative,Instagram,neutral,0

In [32]:
df['prediction_correctness_nltk'].value_counts()

prediction_correctness_nltk
1    323
0    176
Name: count, dtype: int64

## Using textblob

In [33]:
! pip install textblob

Collecting textblob
  Downloading textblob-0.19.0-py3-none-any.whl.metadata (4.4 kB)
Collecting nltk>=3.9 (from textblob)
  Downloading nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: click in c:\users\vvenk\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.1.7)
Requirement already satisfied: joblib in c:\users\vvenk\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\vvenk\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2023.10.3)
Requirement already satisfied: tqdm in c:\users\vvenk\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\users\vvenk\appdata\roaming\python\python311\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Downloading textblob-0.19.0-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
    --------------------------------------- 10.2/624.3 kB ? eta -:--:--
    --------------------------------------- 10.2/624.3 kB ? eta -:--:--
    --------------------------------------- 10.2/624.3 kB ? eta -:--:--
   -- ------------------------------------ 41.0/624.3 kB 196.9 kB/s eta 0:00:03
   ------- ------------------------------ 122.9/624.3 kB 554.9 kB/s eta 0:00:01
   ----------- -------------------------- 194.6/624.3 kB 787.7 kB/s eta 0:00:01
   ----------- -------------------------- 194.6/624.3 kB 787.7 kB/s eta 0:00:01
   ------------- ------------------------ 225.3/624.3 kB 655.6 kB/s eta 0:00:01
   ------------- ------------------------ 225.3/624.3 kB 655.6 kB/s eta 0:00:01
   ------------- ------------------------ 225.3/624.3 kB 655.6 kB/s eta 0:00:01
   ------------------- ------------------ 317.4/624.3 kB 655.0 kB/s eta 0:00:01
   ----------------------------- -------- 481.3/624.3 kB 887.1 kB/s eta 0:00:01
   -------------------------------- ----- 532.5/624.3 kB 903.5 kB/s eta 0:00:01
   ---------------------------------------  614.4/624.3 kB 1.0 MB/s eta 0:00:01
   -------------------------------------- 624.3/624.3 kB 957.9 kB/s eta 0:00:00
Downloading nltk-3.9.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.2/1.5 MB 5.6 MB/s eta 0:00:01
   ----------- ---------------------------- 0.4/1.5 MB 4.4 MB/s eta 0:00:01
   ------------- -------------------------- 0.5/1.5 MB 4.6 MB/s eta 0:00:01
   -------------- ------------------------- 0.6/1.5 MB 3.2 MB/s eta 0:00:01
   -------------- ------------------------- 0.6/1.5 MB 3.2 MB/s eta 0:00:01
   -------------- ------------------------- 0.6/1.5 MB 3.2 MB/s eta 0:00:01
   ----------------- ---------------------- 0.7/1.5 MB 2.1 MB/s eta 0:00:01
   ----------------------- ---------------- 0.9/1.5 MB 2.3 MB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.5 MB 2.6 MB/s eta 0:00:01
   ------------------------------- -------- 1.2/1.5 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 1.3/1.5 MB 2.7 MB/s eta 0:00:01
   ----------------------------------- ---- 1.3/1.5 MB 2.7 MB/s eta 0:00:01
   ----------------------------------- ---- 1.4/1.5 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  1.5/1.5 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 2.2 MB/s eta 0:00:00
Installing collected packages: nltk, textblob
  Attempting uninstall: nltk
    Found existing installation: nltk 3.8.1
    Uninstalling nltk-3.8.1:
      Successfully uninstalled nltk-3.8.1
Successfully installed nltk-3.9.1 textblob-0.19.0

In [36]:
from textblob import TextBlob

In [38]:
def analyze_sentiment_textblob(review):
    blob = TextBlob(review)
    if blob.sentiment.polarity >= 0.4:
        return 'positive'
    elif blob.sentiment.polarity >= -0.3 and blob.sentiment.polarity <= 0.4:
        return 'neutral'
    else : 
        return 'negative'

In [39]:
analyze_sentiment_textblob('This is a good movie')

'positive'

In [40]:
df['predicted_sentiment_textblob'] = df['text'].apply(analyze_sentiment_textblob)

In [41]:
df['prediction_correctness_textblob'] = np.where(df['sentiment']==df['predicted_sentiment_textblob'],1,0)

In [45]:
df

,Year,Month,Day,Time of Tweet,text,sentiment,Platform,predicted_sentiment_nltk,prediction_correctness_nltk,predicted_sentiment_textblob,prediction_correctness_textblob
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter,positive,1,positive,1
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook,neutral,0,negative,0
2,2017,8,18,night,Don't angry me,negative,Facebook,positive,0,negative,1
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook,neutral,0,neutral,0
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram,neutral,0,neutral,0
...,...,...,...,...,...,...,...,...,...,...,...
494,2015,10,18,night,"According to , a quarter of families under six...",negative,Twitter,negative,1,neutral,0
495,2021,2,25,morning,the plan to not spend money is not going well,negative,Instagram,neutral,0,neutral,0
496,2022,5,30,noon,uploading all my bamboozle pictures of facebook,neutral,Facebook,negative,0,neutral,1
497,2018,8,10,night,congratulations ! you guys finish a month ear...,positive,Twitter,positive,1,neutral,0
498,2019,3,25,morning,"actually, I wish I was back in Tahoe. I miss...",negative,Instagram,neutral,0,neutral,0

In [44]:
df['prediction_correctness_textblob'].value_counts()

prediction_correctness_textblob
1    283
0    216
Name: count, dtype: int64